### PR TITLE
Master

### PR DESCRIPTION
**Pull request by bthomson2**
Added functions to Set, Get and Change border color. 

To test,: 
Open CSnap locally. 
Do a File-> Import-> (a local copy of Graffiti.xml)
In the script, remove the "set border color to pen color" block. 
Sub in, "Set border shade to" and change the default to 0.
Run the app to see that the border color is now black. 

For further testing, lower in the script, (the if-else statement) you can sub in the "change border shade by ?" or "set border shade to" blocks. 

Future consideration: Should we get rid of the "Set border color to" block?

### CODE REVIEW

**Comment by SillyInventor** [comment]
This pull cannot be made... it looks like the setup for your repository is not correct... you need to fork this CSnap repository, and make those changes, and then make the pull request...

**Comment by SillyInventor** [comment]
Also, to test, one should always copy this into their local version of the website, and test all relevant features... anything else is incomplete testing.

**Comment by chuck211991** [comment]
Hi Brenda,

It looks like you committed your code to master without a code review, then attempted to make a pull request to the branch csnap (which is legacy at this point). I deleted your commit; it would be easier for you to make a new clone of the repository, copy your code into it, then try again. Do you have time to meet this week? I'm curious to know what you did; it shouldn't be allowed.

Thanks,
  Charles

**Comment by ibara** [comment]
Thanks Charles.

**Pull request closed without merging**
