### PR TITLE
Fixing some of the login from CSnap problems

### PR DESCRIPTION
**Pull request by SillyInventor**
The login should work now... apparently someone configured the request wrong.

The getProjectsList command should now request log in if not logged in.

### CODE REVIEW

**Comment by SillyInventor** [comment]
Before the classroom selection in CSnap will work properly, you will have to merge the pull for rpi_csdt_community.

**Comment by ibara** [comment]
OK. As you probably say from my email earlier today, I'm just waiting on Brenda to get things moving.

**Comment by SillyInventor** [comment]
No rush.

**Comment by SillyInventor** [comment]
To fix some problems with the new dev site updates... this needs to be merged. I will do some thorough testing on the dev site first.

**Pull request merged**
